### ISSUE TITLE
Cannot resolve dependencies

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#57] opened 2018-11-05 14:40 UTC
yarn install doesn't work right now

> error C:\xampp\htdocs\app.mathcitymap\node_modules\node-expat: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\xampp\htdocs\app.mathcitymap\node_modules\node-expat
Output:
C:\xampp\htdocs\app.mathcitymap\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\app.mathcitymap\\node_modules\\node-expat\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bauma\\.node-gyp\\8.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\bauma\\.node-gyp\\8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\bauma\\.node-gyp\\8.12.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\app.mathcitymap\\node_modules\\node-expat',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\xampp\\htdocs\\app.mathcitymap\\node_modules\\node-expat\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\xampp\htdocs\app.mathcitymap\node_modules\node-expat\build\deps\libexpat\..\..\..\deps\libexpat\version.c
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
MSBUILD : error MSB4132: Unbekannte Toolsversion 2.0. Verf�gbare Toolsversionen sind "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\app.mathcitymap\node_modules\node-expat
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0

>

**Comment by am-immanuel** [comment] 2018-11-26 10:42
The root cause is this: »MSBUILD : error MSB4132: Unbekannte Toolsversion 2.0. Verfügbare Toolsversionen sind "4.0".«

Based on https://github.com/chjj/pty.js/issues/60#issuecomment-340522481, could you please try to run these lines?
```
$ npm install --global --production windows-build-tools
$ yarn config set msvs_version 2015 --global
```

**Comment by baumwehn** [comment] 2018-11-26 10:48
uninstalling python 3.7 resolved that problem for me. it seems that yarn needs pytrhon 2.7

**Comment by am-immanuel** [comment] 2018-11-26 10:50
Okay, great. If the issue is solved for you, I close it.

**Closed by am-immanuel** 2018-11-26 10:50 UTC
